---
- name: Ce playbook installe LAMP et Wordpress
  hosts: web1
  vars_files:
    - vars.yml
  roles:
    - role: common
    - role: apache2
    - role: mariadb
    - role: folders
    - role: wordpress
    - role: php