---
- name: Update repositories cache and install htop, screen, open-vm-tools package
  become: yes
  apt:
    name:
      - htop
      - open-vm-tools
      - dnsutils
      - curl
      - net-tools
      - iptables
      - parted
      - gnupg
      - apt-transport-https 
      - lsb-release 
      - ca-certificates
      - wget
      - php
    state : present
    update_cache: yes
