---

- name: Update repositories cache and install htop, screen, open-vm-tools package
  become: yes
  apt:
    name:
      - htop
      - open-vm-tools
      - dnsutils
      - curl
      - net-tools
      - iptables
    state : present
    update_cache: yes
    cache_valid_time: 3600
